all: gllvm2.dll gllvm3.dll
	# Comment here preserves the prior tab
gllvm2.dll: gllvm2.cpp
	Rscript --vanilla -e "TMB::compile('gllvm2.cpp', '-O1 -g',DLLFLAGS='')"
		# Comment here preserves the prior tab
gllvm3.dll: gllvm3.cpp
	Rscript --vanilla -e "TMB::compile('gllvm3.cpp', '-O1 -g',DLLFLAGS='')"
	
clean:
	rm -rf *.dll
